Vidya/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidya.Models
{
    public class Game
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        [Required]
        public Genre Genre { get; set; }
        public byte GenreId { get; set; }

        [Required]
        public Console Console { get; set; }
        public byte ConsoleId { get; set; }

        public DateTime ReleaseDate { get; set; }
        public DateTime DateAdded { get; set; }

        public byte NumberInStock { get; set; }
    }
}

Vidya/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidya.Models;

namespace Vidya.Controllers
{
    public class GamesController : Controller
    {
        private ApplicationDbContext _context;
        
        public GamesController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        
        public ViewResult Index()
        {
            var games = _context.Games.Include(g => g.Genre).ToList();

            return View(games);
        }

        public ActionResult Details(int id)
        {
            var game = _context.Games
                .Include(g => g.Genre)
                .Include(g => g.Console)
                .SingleOrDefault(g => g.Id == id);

            if (game == null)
                return HttpNotFound();

            return View(game);
        }
    }
}

Vidya/Views/Games/Details.cshtml
@model Vidya.Models.Game

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

<ul>
    <li>Genre: @Model.Genre.Name</li>
    <li>Console: @Model.Console.Name</li>
    <li>Release Date: @Model.ReleaseDate.ToString("MMMM dd, yyyy")</li>
    <li>Date Added: @Model.DateAdded.ToString("dddd, MMMM dd, yyyy")</li>
    <li>Number in Stock: @Model.NumberInStock</li>
</ul>

Vidya/Views/Games/Index.cshtml
@model IEnumerable<Vidya.Models.Game>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Games</h2>

@if (!Model.Any())
{
    <text>We don't have any games yet.</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Game</th>
                <th>Genre</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var game in Model)
            {
            <tr>
                <td>@Html.ActionLink(game.Name, "Details", "Games", new { id = game.Id }, null)</td>
                <td>@game.Genre.Name</td>
            </tr>
            }
        </tbody>
    </table>
}